services:
  nginx:
    image: nginx:latest
    container_name: quartz_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: unless-stopped

